#!/usr/bin/env bash
set -euo pipefail

# ============================================================================
# bootstrap.sh — one-time setup of the Terraform state backend.
#
# Creates (idempotently):
#   - Resource group:    lt-tfstate-rg              (separate from lt-rg)
#   - Storage account:   lttfstate<suffix>          (deterministic suffix)
#   - Blob container:    tfstate
# Writes:
#   - ../backend.tfvars  with the values needed by `terraform init`
#
# Usage:
#   cd infra-terraform/bootstrap && ./bootstrap.sh
# ============================================================================

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TF_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"

LOCATION="uksouth"
STATE_RG="lt-tfstate-rg"
STATE_CONTAINER="tfstate"

# Match deploy.sh's suffix: sha256(subscription_id) | first 6 hex chars
SUB_ID=$(az account show --query "id" -o tsv | tr -d '\r')
SUFFIX=$(printf '%s' "$SUB_ID" | openssl dgst -sha256 2>/dev/null | sed 's/.*= //' | cut -c1-6)
STATE_SA="lttfstate${SUFFIX}"

echo "============================================"
echo "Terraform state bootstrap"
echo "============================================"
echo "Subscription:     $SUB_ID"
echo "Resource group:   $STATE_RG"
echo "Storage account:  $STATE_SA"
echo "Container:        $STATE_CONTAINER"
echo "============================================"
echo ""

echo ">> Resource group..."
az group create --name "$STATE_RG" --location "$LOCATION" --output none

echo ">> Storage account..."
if az storage account show --name "$STATE_SA" --resource-group "$STATE_RG" --output none 2>/dev/null; then
    echo "   Already exists, skipping."
else
    az storage account create \
        --name "$STATE_SA" \
        --resource-group "$STATE_RG" \
        --location "$LOCATION" \
        --sku Standard_LRS \
        --encryption-services blob \
        --allow-blob-public-access false \
        --output none
fi

echo ">> Blob container..."
az storage container create \
    --name "$STATE_CONTAINER" \
    --account-name "$STATE_SA" \
    --auth-mode login \
    --output none

# ---------------------------------------------------------------------------
# Write backend.tfvars
# ---------------------------------------------------------------------------
BACKEND_TFVARS="$TF_DIR/backend.tfvars"
cat > "$BACKEND_TFVARS" <<EOF
# Auto-generated by bootstrap.sh — safe to commit (no secrets).
resource_group_name  = "${STATE_RG}"
storage_account_name = "${STATE_SA}"
container_name       = "${STATE_CONTAINER}"
key                  = "letter-translation.tfstate"
EOF

echo ""
echo "============================================"
echo "Bootstrap complete!"
echo "============================================"
echo "Wrote: $BACKEND_TFVARS"
echo ""
echo "Next steps:"
echo "  cd $TF_DIR"
echo "  cp terraform.tfvars.example terraform.tfvars  # then edit"
echo "  terraform init -backend-config=backend.tfvars"
echo "  terraform plan"
echo ""
