# Auto-generated by bootstrap.sh — safe to commit (no secrets).
resource_group_name  = "lt-tfstate-rg"
storage_account_name = "lttfstateb2b4c4"
container_name       = "tfstate"
key                  = "letter-translation.tfstate"
